# Project 3 -- [Niharika] [Rai]

**TA Help:** N/A
    
**Collaboration:** N/A

## Question 1

In [6]:
import os 
os.listdir("/anvil/projects/tdm/data/noaa")

['1957.csv',
 '1972.csv',
 '1854.csv',
 '1902.csv',
 '1878.csv',
 '1775.csv',
 '1808.csv',
 '1966.csv',
 '1981.csv',
 '1863.csv',
 '1911.csv',
 '1887.csv',
 '1769.csv',
 '1935.csv',
 '1784.csv',
 '1817.csv',
 '1832.csv',
 '2007.csv',
 '1990.csv',
 '1999.csv',
 '1896.csv',
 '1929.csv',
 '1944.csv',
 '1793.csv',
 '1826.csv',
 '1841.csv',
 '2016.csv',
 '1953.csv',
 '1850.csv',
 '1977.csv',
 '1859.csv',
 '1874.csv',
 '1907.csv',
 '1922.csv',
 '1771.csv',
 '1804.csv',
 '1962.csv',
 '1986.csv',
 '1868.csv',
 '1883.csv',
 '1916.csv',
 '1765.csv',
 '1931.csv',
 '1780.csv',
 '1813.csv',
 '2003.csv',
 '1789.csv',
 '1837.csv',
 '1995.csv',
 '1892.csv',
 '1925.csv',
 '1940.csv',
 '1822.csv',
 '2012.csv',
 '1949.csv',
 '1798.csv',
 '1846.csv',
 '2021.csv',
 '1958.csv',
 '1973.csv',
 '1855.csv',
 '1870.csv',
 '1903.csv',
 '1800.csv',
 '1879.csv',
 '1776.csv',
 '1809.csv',
 '1967.csv',
 '1982.csv',
 '1864.csv',
 '1912.csv',
 '1888.csv',
 '1936.csv',
 '1785.csv',
 '1818.csv',
 '1833.csv',
 '2008.csv',
 '1991.csv',
 '1897.csv',
 '1945.csv',
 '1794.csv',
 '1960.csv',
 '1827.csv',
 '1842.csv',
 '2017.csv',
 '1954.csv',
 '1851.csv',
 '1978.csv',
 '1875.csv',
 '1908.csv',
 '1772.csv',
 '1805.csv',
 '1820.csv',
 '1963.csv',
 '1860.csv',
 '1987.csv',
 '1869.csv',
 '1884.csv',
 '1917.csv',
 '1766.csv',
 '1932.csv',
 '1781.csv',
 '1814.csv',
 '2004.csv',
 '1838.csv',
 '1996.csv',
 '1893.csv',
 '1926.csv',
 '1941.csv',
 '1790.csv',
 '1823.csv',
 '2013.csv',
 '1799.csv',
 '1847.csv',
 '1950.csv',
 '2022.csv',
 '1959.csv',
 '1974.csv',
 '1856.csv',
 '1871.csv',
 '1904.csv',
 '1801.csv',
 '1777.csv',
 '1968.csv',
 '1983.csv',
 '1865.csv',
 '1880.csv',
 '1913.csv',
 '1810.csv',
 '2000.csv',
 '1889.csv',
 '1937.csv',
 '1786.csv',
 '1819.csv',
 '1834.csv',
 '2009.csv',
 '1992.csv',
 '1898.csv',
 '1946.csv',
 '1795.csv',
 '1961.csv',
 '1828.csv',
 '1843.csv',
 '2018.csv',
 '1955.csv',
 '1970.csv',
 '1852.csv',
 '1900.csv',
 '1979.csv',
 '1876.csv',
 '1909.csv',
 '1773.csv',
 '1806.csv',
 '1964.csv',
 '1861.csv',
 '1988.csv',
 '1885.csv',
 '1918.csv',
 '1767.csv',
 '1933.csv',
 '1782.csv',
 '1815.csv',
 '1830.csv',
 '2005.csv',
 '1839.csv',
 '1997.csv',
 '1894.csv',
 '1927.csv',
 '1942.csv',
 '1791.csv',
 '1824.csv',
 '2014.csv',
 '1848.csv',
 '1951.csv',
 '2023.csv',
 '1975.csv',
 '1857.csv',
 '1872.csv',
 '1905.csv',
 '1920.csv',
 '1802.csv',
 '1778.csv',
 '1969.csv',
 '1984.csv',
 '1866.csv',
 '1881.csv',
 '1914.csv',
 '1763.csv',
 '1811.csv',
 '2001.csv',
 '1938.csv',
 '1787.csv',
 '1835.csv',
 '1993.csv',
 '1890.csv',
 '1923.csv',
 '2010.csv',
 '1899.csv',
 '1947.csv',
 '1796.csv',
 '1829.csv',
 '1844.csv',
 '2019.csv',
 '1956.csv',
 '1971.csv',
 '1853.csv',
 '1901.csv',
 '1750.csv',
 '1877.csv',
 'status-by_year.txt',
 '1774.csv',
 '1807.csv',
 '1965.csv',
 '1980.csv',
 '1862.csv',
 '1910.csv',
 '1989.csv',
 '1886.csv',
 '1919.csv',
 '1768.csv',
 '1934.csv',
 '1783.csv',
 '1816.csv',
 '1831.csv',
 '2006.csv',
 '2020_sample.csv',
 '1998.csv',
 '1895.csv',
 '1928.csv',
 '1943.csv',
 '1792.csv',
 '1825.csv',
 'readme-by_year.txt',
 '1840.csv',
 '2015.csv',
 '1849.csv',
 '1952.csv',
 '1976.csv',
 '1858.csv',
 '1873.csv',
 '1906.csv',
 '1921.csv',
 '1770.csv',
 '1803.csv',
 '1779.csv',
 '2020_sampleB.csv',
 '1985.csv',
 '1867.csv',
 '1882.csv',
 '1915.csv',
 '1764.csv',
 '1930.csv',
 '1812.csv',
 '2002.csv',
 '1939.csv',
 '1788.csv',
 '1836.csv',
 '1994.csv',
 '1891.csv',
 '1924.csv',
 '1821.csv',
 '2011.csv',
 '1948.csv',
 '1797.csv',
 '1845.csv',
 '2020.csv']

In [5]:
len(os.listdir("/anvil/projects/tdm/data/noaa"))

266

In [7]:
import pandas as pd
from pathlib import Path
Path("/anvil/projects/tdm/data/noaa/1880.csv")

PosixPath('/anvil/projects/tdm/data/noaa/1880.csv')

In [8]:
myfiles=[]
for year in range (1880, 1884):
    file= Path(f'/anvil/projects/tdm/data/noaa/{year}.csv')
    myfiles.append(file)
print(myfiles)

[PosixPath('/anvil/projects/tdm/data/noaa/1880.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1881.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1882.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1883.csv')]

In [9]:
myfiles = [Path(f'/anvil/projects/tdm/data/noaa/{year}.csv') for year in range (1880, 1884)] 
print(myfiles)

[PosixPath('/anvil/projects/tdm/data/noaa/1880.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1881.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1882.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1883.csv')]

I got this code from the 1st video, "How to find the files in a directory in Python". The link to all the videos is here: https://the-examples-book.com/programming-languages/python/looping-through-files. 
Based on part a, the files range from 1763.csv to 2023.csv. There is 1 file for 1750.csv. Then, there are other files such as status-by_year.txt, 2020_sample.csv, readme-by_year.txt and 2020_sampleB.csv. Hence, the total number of files are 266 files.

For part b, I got the code from the same video linked above. There was a typing error in part b of question 1. After watching this video, I used the correct version. 

For part c, I directly used the code given under tip. The link to that tip is here: https://the-examples-book.com/projects/current-projects/10200-2024-project03 
But I later modified that code to include the list comprehension. I took the code structure from the second video, "Example about list comprehensions" from this link: https://the-examples-book.com/programming-languages/python/looping-through-files.

## Question 2

In [6]:
import pandas as pd
from pathlib import Path

file = Path(f'/anvil/projects/tdm/data/noaa/1880.csv')  
with open(file,"r") as f: 
    mycount = 0
    for line in f: 
        mycount += 1 
print(f'There are {mycount} records in the file called {file}')

There are 370779 records in the file called /anvil/projects/tdm/data/noaa/1880.csv

In [7]:
for year in range(1880, 1884, 1): 
    file = Path(f'/anvil/projects/tdm/data/noaa/{year}.csv') 
    with open(file,"r") as f: 
        mycount = 0
        for line in f: 
            mycount += 1
    print(f'There are {mycount} records in the file called {file}')

There are 370779 records in the file called /anvil/projects/tdm/data/noaa/1880.csv
There are 443270 records in the file called /anvil/projects/tdm/data/noaa/1881.csv
There are 514083 records in the file called /anvil/projects/tdm/data/noaa/1882.csv
There are 578730 records in the file called /anvil/projects/tdm/data/noaa/1883.csv

For question 2, part a and b, I followed the code structure from the video, "looping over files to check the number of records" from this link: https://the-examples-book.com/programming-languages/python/looping-through-files. However, I modified my code in context of my question. This involved using the dataset I was given for this project, using 1880

## Question 3

In [4]:
import pandas as pd
from pathlib import Path

myfiles = [] 
for year in range(1880, 1884): 
    file = Path(f'/anvil/projects/tdm/data/noaa/{year}.csv')
    myfiles.append(file)
print(myfiles)

[PosixPath('/anvil/projects/tdm/data/noaa/1880.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1881.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1882.csv'), PosixPath('/anvil/projects/tdm/data/noaa/1883.csv')]

In [7]:
print(myfiles[0])

/anvil/projects/tdm/data/noaa/1880.csv

In [8]:
myDF = [] 
myDF = pd.read_csv(myfiles[0]) 
print(myDF)

        AGE00147705  18800101  PRCP    0 Unnamed: 4 Unnamed: 5  E  Unnamed: 7
0       AGE00147708  18800101  PRCP   36        NaN        NaN  E         NaN
1       AGE00147709  18800101  PRCP   36        NaN        NaN  E         NaN
2       AGE00147712  18800101  PRCP    0        NaN        NaN  E         NaN
3       AGE00147713  18800101  TMAX   52        NaN        NaN  E         NaN
4       AGE00147713  18800101  TMIN    0        NaN        NaN  E         NaN
...             ...       ...   ...  ...        ...        ... ..         ...
370773  USW00093852  18801231  TMAX   39        NaN        NaN  X         NaN
370774  USW00093852  18801231  TMIN  -17        NaN        NaN  X         NaN
370775  USW00094728  18801231  TMAX -122        NaN        NaN  0         NaN
370776  USW00094728  18801231  TMIN -194        NaN        NaN  0         NaN
370777  USW00094728  18801231  PRCP    0        NaN        NaN  0         NaN

[370778 rows x 8 columns]

In [9]:
myDF.columns

Index(['AGE00147705', '18800101', 'PRCP', '0', 'Unnamed: 4', 'Unnamed: 5', 'E',
       'Unnamed: 7'],
      dtype='object')

In [11]:
myDF.head()

   AGE00147705  18800101  PRCP   0 Unnamed: 4 Unnamed: 5  E  Unnamed: 7
0  AGE00147708  18800101  PRCP  36        NaN        NaN  E         NaN
1  AGE00147709  18800101  PRCP  36        NaN        NaN  E         NaN
2  AGE00147712  18800101  PRCP   0        NaN        NaN  E         NaN
3  AGE00147713  18800101  TMAX  52        NaN        NaN  E         NaN
4  AGE00147713  18800101  TMIN   0        NaN        NaN  E         NaN

In [12]:
myDF.tail()

        AGE00147705  18800101  PRCP    0 Unnamed: 4 Unnamed: 5  E  Unnamed: 7
370773  USW00093852  18801231  TMAX   39        NaN        NaN  X         NaN
370774  USW00093852  18801231  TMIN  -17        NaN        NaN  X         NaN
370775  USW00094728  18801231  TMAX -122        NaN        NaN  0         NaN
370776  USW00094728  18801231  TMIN -194        NaN        NaN  0         NaN
370777  USW00094728  18801231  PRCP    0        NaN        NaN  0         NaN

In [14]:
header=None 
myDF.columns

Index(['AGE00147705', '18800101', 'PRCP', '0', 'Unnamed: 4', 'Unnamed: 5', 'E',
       'Unnamed: 7'],
      dtype='object')

In [15]:
pd.read_csv(myfiles[0],names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"])

                 id      date element_code  value mflag qflag sflag  obstime
0       AGE00147705  18800101         PRCP      0   NaN   NaN     E      NaN
1       AGE00147708  18800101         PRCP     36   NaN   NaN     E      NaN
2       AGE00147709  18800101         PRCP     36   NaN   NaN     E      NaN
3       AGE00147712  18800101         PRCP      0   NaN   NaN     E      NaN
4       AGE00147713  18800101         TMAX     52   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
370774  USW00093852  18801231         TMAX     39   NaN   NaN     X      NaN
370775  USW00093852  18801231         TMIN    -17   NaN   NaN     X      NaN
370776  USW00094728  18801231         TMAX   -122   NaN   NaN     0      NaN
370777  USW00094728  18801231         TMIN   -194   NaN   NaN     0      NaN
370778  USW00094728  18801231         PRCP      0   NaN   NaN     0      NaN

[370779 rows x 8 columns]

In [18]:
mydataframes = [] 
for i in range(0,4): 
    mydataframes.append(pd.read_csv(myfiles[i],names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"])) 
print(mydataframes)

[                 id      date element_code  value mflag qflag sflag  obstime
0       AGE00147705  18800101         PRCP      0   NaN   NaN     E      NaN
1       AGE00147708  18800101         PRCP     36   NaN   NaN     E      NaN
2       AGE00147709  18800101         PRCP     36   NaN   NaN     E      NaN
3       AGE00147712  18800101         PRCP      0   NaN   NaN     E      NaN
4       AGE00147713  18800101         TMAX     52   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
370774  USW00093852  18801231         TMAX     39   NaN   NaN     X      NaN
370775  USW00093852  18801231         TMIN    -17   NaN   NaN     X      NaN
370776  USW00094728  18801231         TMAX   -122   NaN   NaN     0      NaN
370777  USW00094728  18801231         TMIN   -194   NaN   NaN     0      NaN
370778  USW00094728  18801231         PRCP      0   NaN   NaN     0      NaN

[370779 rows x 8 columns],                  id      date element_code  value mflag qflag sflag  obstime
0       AGE00135039  18810101         PRCP     30   NaN   NaN     E      NaN
1       AGE00147705  18810101         PRCP    479   NaN   NaN     E      NaN
2       AGE00147708  18810101         PRCP    125   NaN   NaN     E      NaN
3       AGE00147709  18810101         PRCP    125   NaN   NaN     E      NaN
4       AGE00147711  18810101         PRCP      0   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
443265  UZM00038457  18811231         PRCP    100   NaN   NaN     r      NaN
443266  UZM00038457  18811231         TAVG     -3   NaN   NaN     r      NaN
443267  UZM00038618  18811231         TMIN    -71   NaN   NaN     r      NaN
443268  UZM00038618  18811231         PRCP    161   NaN   NaN     r      NaN
443269  UZM00038618  18811231         TAVG    -49   NaN   NaN     r      NaN

[443270 rows x 8 columns],                  id      date element_code  value mflag qflag sflag  obstime
0       AGE00135039  18820101         PRCP      0   NaN   NaN     E      NaN
1       AGE00147705  18820101         PRCP      0   NaN   NaN     E      NaN
2       AGE00147708  18820101         PRCP      0   NaN   NaN     E      NaN
3       AGE00147709  18820101         PRCP      0   NaN   NaN     E      NaN
4       AGE00147711  18820101         PRCP      0   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
514078  UZM00038457  18821231         PRCP      0   NaN   NaN     r      NaN
514079  UZM00038457  18821231         TAVG     16   NaN   NaN     r      NaN
514080  UZM00038618  18821231         TMIN     10   NaN   NaN     r      NaN
514081  UZM00038618  18821231         PRCP      0   NaN   NaN     r      NaN
514082  UZM00038618  18821231         TAVG     33   NaN   NaN     r      NaN

[514083 rows x 8 columns],                  id      date element_code  value mflag qflag sflag  obstime
0       AGE00135039  18830101         PRCP      0   NaN   NaN     E      NaN
1       AGE00147705  18830101         PRCP      0   NaN   NaN     E      NaN
2       AGE00147708  18830101         PRCP      0   NaN   NaN     E      NaN
3       AGE00147709  18830101         PRCP      0   NaN   NaN     E      NaN
4       AGE00147711  18830101         PRCP      0   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
578725  UZM00038457  18831231         PRCP      0   NaN   NaN     r      NaN
578726  UZM00038457  18831231         TAVG    -69   NaN   NaN     r      NaN
578727  UZM00038618  18831231         TMIN    -22   NaN   NaN     r      NaN
578728  UZM00038618  18831231         PRCP      0   NaN   NaN     r      NaN
578729  UZM00038618  18831231         TAVG      1   NaN   NaN     r      NaN

[578730 rows x 8 columns]]

In [30]:
for i in range(0, 4): 
    print(mydataframes[i].columns)

Index(['id', 'date', 'element_code', 'value', 'mflag', 'qflag', 'sflag',
       'obstime'],
      dtype='object')
Index(['id', 'date', 'element_code', 'value', 'mflag', 'qflag', 'sflag',
       'obstime'],
      dtype='object')
Index(['id', 'date', 'element_code', 'value', 'mflag', 'qflag', 'sflag',
       'obstime'],
      dtype='object')
Index(['id', 'date', 'element_code', 'value', 'mflag', 'qflag', 'sflag',
       'obstime'],
      dtype='object')

Something unexpected that I saw in part a was that the last 4 columns are unnamed. I got the code structure from question 1, tip of project 3. To display the column names, head and tail, I types those fuctions by having memorized them from the works I did in the previous 2 projects. I also referred to part d which said to use myDF.columns to display the column names. I also used this website as a reference: https://note.nkmk.me/en/python-pandas-len-shape-size/. For part b, I used the hint: header=None and it gave me the same result that there are no column names. Instead of keeping everything on the same line, I created my own code structure and wrote them out separately in different lines. For part c, I used the code structure from the question itself. For part d, I got the code structure from the video, "reading in data frames in a loop" from this link: https://the-examples-book.com/programming-languages/python/looping-through-files. However, I added an additional step of print(mydataframes) so that I can see all the rows and columns at the same time. Furthermore, I even checked my work using loop to see that each of the data files from 1880.csv to 1883.csv have had a change in column names. I got the code structure from a video called, "". linked above. But, instead of using shape, I used columns by taking an exemplar reference of myDF.columns from part d of the question.

## Question 4

In [11]:
import pandas as pd
from pathlib import Path

myfiles = [] 
for year in range(1880, 1884): 
    file = Path(f'/anvil/projects/tdm/data/noaa/{year}.csv')
    myfiles.append(file) 
    
myDF = [] 
myDF = pd.read_csv(myfiles[0]) 
print(myDF) 

mydataframes = [] 
for i in range(0,4): 
    mydataframes.append(pd.read_csv(myfiles[i],names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"])) 
    
for myDF in mydataframes: 
    print(myDF['element_code'].unique())

        AGE00147705  18800101  PRCP    0 Unnamed: 4 Unnamed: 5  E  Unnamed: 7
0       AGE00147708  18800101  PRCP   36        NaN        NaN  E         NaN
1       AGE00147709  18800101  PRCP   36        NaN        NaN  E         NaN
2       AGE00147712  18800101  PRCP    0        NaN        NaN  E         NaN
3       AGE00147713  18800101  TMAX   52        NaN        NaN  E         NaN
4       AGE00147713  18800101  TMIN    0        NaN        NaN  E         NaN
...             ...       ...   ...  ...        ...        ... ..         ...
370773  USW00093852  18801231  TMAX   39        NaN        NaN  X         NaN
370774  USW00093852  18801231  TMIN  -17        NaN        NaN  X         NaN
370775  USW00094728  18801231  TMAX -122        NaN        NaN  0         NaN
370776  USW00094728  18801231  TMIN -194        NaN        NaN  0         NaN
370777  USW00094728  18801231  PRCP    0        NaN        NaN  0         NaN

[370778 rows x 8 columns]
['PRCP' 'TMAX' 'TMIN' 'SNOW' 'SNWD' 'TAVG' 'MDPR' 'DATN' 'DATX' 'MDTN'
 'MDTX' 'DAPR' 'DWPR' 'MDSF' 'WT01' 'TOBS' 'WT04' 'WT05']
['PRCP' 'TMAX' 'TMIN' 'TAVG' 'SNOW' 'SNWD' 'MDPR' 'MDSF' 'DATN' 'DATX'
 'MDTN' 'MDTX' 'WT04' 'DAPR' 'DWPR' 'TOBS']
['PRCP' 'TMAX' 'TMIN' 'TAVG' 'SNOW' 'SNWD' 'DATN' 'DATX' 'MDTN' 'MDTX'
 'DAPR' 'DWPR' 'MDPR' 'MDSF' 'WT04' 'TOBS' 'WT05' 'WT03' 'WT16' 'WT18'
 'DASF']
['PRCP' 'TMAX' 'TMIN' 'TAVG' 'SNOW' 'SNWD' 'DAPR' 'DWPR' 'MDPR' 'MDSF'
 'WT11' 'DATN' 'DATX' 'MDTN' 'MDTX' 'WT03' 'DASF' 'WT18' 'WT04' 'WT16'
 'WT08']

In [13]:
for myDF in mydataframes: 
    print(myDF['element_code'].value_counts()['SNOW'])

33700
36451
40648
53417

For part a, I used the code structure from the video, "finding unique elements in a column of a data frame", linked in the examples book: https://the-examples-book.com/programming-languages/python/looping-through-files. But before that, I also had to input part of the codes that I wrote in question 3 because otherwise it was giving me an error as Path, pd, mydataframes, and myfiles were not defined. To ensure that the element_codes are different, I used the len fuction to calculate the number of elements in each of these dataframes. Hence, the different values indicate that each data frame had a different information displayed under the element_code column. 

For part b, I got the code structure from a video titled, "finding value counts in columns of a list of data frames" linked in the examples book: https://the-examples-book.com/programming-languages/python/looping-through-files.

## Question 5

In [3]:
import pandas as pd
from pathlib import Path
myfiles=[]
for year in range (1880, 1884):
    file= Path(f'/anvil/projects/tdm/data/noaa/{year}.csv')
    myfiles.append(file) 
    
count = 0
for file in myfiles:
    for myDF in pd.read_csv(file,names=["id","date","element_code","value","mflag","qflag","sflag","obstime"],chunksize =10000):
        count += len(myDF[myDF['element_code'] == 'SNOW'])

print(count)

164216

In [4]:
count = 0
for file in myfiles:
    for myDF in pd.read_csv(file,names=["id","date","element_code","value","mflag","qflag","sflag","obstime"],chunksize =10000):
        for index, row in myDF.iterrows():
            if row['element_code'] == 'SNOW':
                count += 1

print(count)

164216

For part a, I got all the codes from the question. Both versions of the program lead to the same answer. This answer is found by adding: 33700+36451+40648+53417 = 164216. This is because the question asked to find how many times 'SNOW' occured in each of the data frames and hence, the answer was the sum of the values in each of the 4 data frames where 'SNOW' occurred. According to this website: https://www.geeksforgeeks.org/how-to-load-a-massive-file-as-small-chunks-in-pandas/, chunksize is basicially the number of rows that are read at 1 given time by the file in pandas. So, if the chunksize in this case is 10000 and the number of rows in the 1880.csv file is 370779, then the number of rows read at once are in 370779/10000 = 37 chunks. The remaining 0779 form the 38th chunk. However, another important point I found out from the same website was that chunksize does not affect the columns in anyway. So, the 8 columns that we have in each of the data frames from 1880.csv to 1883.csv stay as they are.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.