# Project 9 -- [Niharika] [Rai]

**TA Help:** N/A
    
**Collaboration:** N/A

## Question 1

In [1]:
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/whin/weather.csv")
pd.set_option('display.max_columns', None)
myDF.head()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
0,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.05,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0
1,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.04,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0
2,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.89,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0
3,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.88,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0
4,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.88,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0

In [2]:
myDF.shape

(1000000, 26)

In [3]:
myDF.dtypes

station_id                       int64
latitude                       float64
longitude                      float64
name                            object
observation_time                object
temperature                    float64
temperature_high               float64
temperature_low                float64
humidity                       float64
solar_radiation                float64
solar_radiation_high           float64
rain                           float64
rain_inches_last_hour          float64
wind_speed_mph                 float64
wind_direction_degrees         float64
wind_gust_speed_mph            float64
wind_gust_direction_degrees    float64
pressure                       float64
soil_temp_1                    float64
soil_temp_2                    float64
soil_temp_3                    float64
soil_temp_4                    float64
soil_moist_1                   float64
soil_moist_2                   float64
soil_moist_3                   float64
soil_moist_4                   float64
dtype: object

In [4]:
myDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 26 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   station_id                   1000000 non-null  int64
 1   latitude                     1000000 non-null  float64
 2   longitude                    1000000 non-null  float64
 3   name                         1000000 non-null  object
 4   observation_time             1000000 non-null  object
 5   temperature                  995824 non-null   float64
 6   temperature_high             995877 non-null   float64
 7   temperature_low              995877 non-null   float64
 8   humidity                     995838 non-null   float64
 9   solar_radiation              951896 non-null   float64
 10  solar_radiation_high         987172 non-null   float64
 11  rain                         1000000 non-null  float64
 12  rain_inches_last_hour        1000000 non-null  float64
 13  wind_speed_mph               995968 non-null   float64
 14  wind_direction_degrees       904455 non-null   float64
 15  wind_gust_speed_mph          1000000 non-null  float64
 16  wind_gust_direction_degrees  905784 non-null   float64
 17  pressure                     1000000 non-null  float64
 18  soil_temp_1                  885957 non-null   float64
 19  soil_temp_2                  885959 non-null   float64
 20  soil_temp_3                  885963 non-null   float64
 21  soil_temp_4                  885964 non-null   float64
 22  soil_moist_1                 885876 non-null   float64
 23  soil_moist_2                 885830 non-null   float64
 24  soil_moist_3                 885826 non-null   float64
 25  soil_moist_4                 885850 non-null   float64
dtypes: float64(23), int64(1), object(2)
memory usage: 198.4+ MB

In [5]:
myDF.describe()

,station_id,latitude,longitude,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
count,1000000.000000,1000000.000000,1000000.000000,995824.000000,995877.000000,995877.000000,995838.000000,951896.000000,987172.000000,1000000.000000,1000000.000000,995968.000000,904455.000000,1000000.000000,905784.000000,1000000.000000,885957.000000,885959.000000,885963.000000,885964.000000,885876.000000,885830.000000,885826.000000,885850.000000
mean,136.811227,40.575033,-86.819166,54.332357,54.641001,54.022909,75.550037,180.700083,1379.200976,0.089229,1.192975,5.914523,184.143938,10.203489,183.210393,29.475522,55.532219,56.951872,55.318035,55.059858,37.796737,33.530907,30.350393,33.378197
std,49.921502,0.272393,0.393169,20.018870,20.052581,19.987283,16.484402,272.963957,6060.627577,1.018177,46.882968,4.867768,97.478143,7.238774,98.011759,0.387023,16.508854,18.499756,14.423309,13.405032,51.850741,51.576801,49.986007,55.127205
min,1.000000,40.104830,-87.510340,-90.000000,-90.000000,-90.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,27.754000,25.000000,28.000000,30.000000,32.000000,0.000000,0.000000,0.000000,0.000000
25%,144.000000,40.384007,-87.148604,39.000000,39.000000,39.000000,66.000000,0.000000,0.000000,0.000000,0.000000,2.000000,90.000000,4.000000,90.000000,29.213000,40.000000,42.000000,42.000000,43.000000,5.000000,4.000000,3.000000,3.000000
50%,153.000000,40.537220,-86.737141,56.000000,57.000000,56.000000,80.000000,11.000000,26.000000,0.000000,0.000000,5.000000,202.500000,9.000000,202.500000,29.372000,55.000000,56.000000,55.000000,54.000000,15.000000,10.000000,8.000000,8.000000
75%,163.000000,40.844360,-86.474180,70.000000,71.000000,70.000000,89.000000,288.000000,415.000000,0.000000,0.000000,9.000000,270.000000,14.000000,270.000000,29.644000,70.000000,71.000000,69.000000,68.000000,45.000000,34.000000,28.000000,31.000000
max,179.000000,41.018650,-86.181730,96.000000,96.000000,96.000000,100.000000,1338.000000,32767.000000,101.000000,8229.000000,37.000000,337.500000,60.000000,337.500000,30.887000,133.000000,164.000000,120.000000,123.000000,200.000000,200.000000,200.000000,200.000000

In [29]:
myDF['station_id'].value_counts()

station_id
1      71631
20     56917
147    45600
143    45593
146    45579
145    45509
144    45495
142    45395
149    44060
159    43563
153    43559
157    43534
155    42993
160    42810
156    42807
151    42806
164    38791
163    37908
166    30242
167    27463
168    18581
169    14905
172    14812
179    14772
176    14402
173    13648
175    13314
171    13311
Name: count, dtype: int64

In [33]:
myDF.groupby(['station_id'])

In [30]:
myDF.groupby(['station_id']).size()

station_id
1      71631
20     56917
142    45395
143    45593
144    45495
145    45509
146    45579
147    45600
149    44060
151    42806
153    43559
155    42993
156    42807
157    43534
159    43563
160    42810
163    37908
164    38791
166    30242
167    27463
168    18581
169    14905
171    13311
172    14812
173    13648
175    13314
176    14402
179    14772
dtype: int64

Before I started part a and b, I explored the csv file according to the tip above question 1 in order to better understand it. When I used the value_counts() method, I instantly found the the number of records in each station. However, when I used the groupby method, I first got a statement and then for the second code, I added the .size() function after grouping the data based on 'station-id' and then got a similar result as I did when using the value_counts method. I think that the major difference between the 2 different methodologies is that groupby will first sort the data based the given parameter such as 'station_id' but then an additional command such as '.size()' needs to be given to get the final output (total number of records). However, the value_counts method just give me the output based on the number of records in each station. One major thing that I have noticed is that the groupby method is outputing more station ids that the value_counts method did not output. This slightly confuses me as I do not know which is more reliable. For that I wached the hint video, "hints for Question 1 on TDM 10200 Project 9" linked here: https://the-examples-book.com/programming-languages/python/hints-for-TDM-10200-project-9. Given that the question asks for the number of records for each station and the groupby shows a lot more station ids, I feel that the groupby method is more reliable. Therefore, I prefer to use the groupby method to get the number of records as it is more reliable, accurate and efficiently presents more number of records based on their unique station ids.

## Question 2

In [37]:
myDF.isnull()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
0,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True
999996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
999997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
999998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
999999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True

In [38]:
myDF.isnull().sum()

station_id                          0
latitude                            0
longitude                           0
name                                0
observation_time                    0
temperature                      4176
temperature_high                 4123
temperature_low                  4123
humidity                         4162
solar_radiation                 48104
solar_radiation_high            12828
rain                                0
rain_inches_last_hour               0
wind_speed_mph                   4032
wind_direction_degrees          95545
wind_gust_speed_mph                 0
wind_gust_direction_degrees     94216
pressure                            0
soil_temp_1                    114043
soil_temp_2                    114041
soil_temp_3                    114037
soil_temp_4                    114036
soil_moist_1                   114124
soil_moist_2                   114170
soil_moist_3                   114174
soil_moist_4                   114150
dtype: int64

In [2]:
myDF.isnull().sum().sum()

1184084

In [39]:
myDF.dropna()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
12823,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:15:00Z,52.0,52.0,52.0,94.0,31.0,42.0,0.0,0.0,19.0,225.0,29.0,225.0,29.805,46.0,44.0,44.0,44.0,7.0,14.0,11.0,9.0
12824,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:30:00Z,52.0,52.0,52.0,94.0,24.0,32.0,0.0,0.0,20.0,225.0,29.0,225.0,29.805,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12825,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:45:00Z,52.0,52.0,52.0,95.0,23.0,26.0,0.0,0.0,20.0,225.0,27.0,225.0,29.810,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12826,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:00:00Z,52.0,52.0,52.0,94.0,29.0,46.0,0.0,0.0,19.0,225.0,27.0,225.0,29.813,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12827,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:15:00Z,52.0,52.0,52.0,95.0,17.0,25.0,0.0,0.0,19.0,225.0,27.0,225.0,29.814,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973747,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:00:00Z,42.0,42.0,42.0,78.0,0.0,0.0,0.0,0.0,1.0,337.5,3.0,337.5,30.283,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973748,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:15:00Z,42.0,42.0,42.0,79.0,0.0,0.0,0.0,0.0,0.0,337.5,2.0,337.5,30.286,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973749,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:30:00Z,41.0,42.0,41.0,79.0,0.0,0.0,0.0,0.0,1.0,337.5,2.0,337.5,30.287,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973750,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:45:00Z,41.0,41.0,41.0,79.0,0.0,0.0,0.0,0.0,1.0,337.5,4.0,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973751,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T05:00:00Z,42.0,42.0,41.0,78.0,0.0,0.0,0.0,0.0,1.0,337.5,4.0,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0

In [17]:
myDF_cleaned = [] 
myDF_cleaned = myDF.dropna() 
myDF_cleaned

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
12823,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:15:00Z,52.0,52.0,52.0,94.0,31.0,42.0,0.0,0.0,19.0,225.0,29.0,225.0,29.805,46.0,44.0,44.0,44.0,7.0,14.0,11.0,9.0
12824,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:30:00Z,52.0,52.0,52.0,94.0,24.0,32.0,0.0,0.0,20.0,225.0,29.0,225.0,29.805,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12825,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T19:45:00Z,52.0,52.0,52.0,95.0,23.0,26.0,0.0,0.0,20.0,225.0,27.0,225.0,29.810,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12826,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:00:00Z,52.0,52.0,52.0,94.0,29.0,46.0,0.0,0.0,19.0,225.0,27.0,225.0,29.813,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
12827,1,40.938940,-86.474180,WHIN001-PULA001,2019-11-21T20:15:00Z,52.0,52.0,52.0,95.0,17.0,25.0,0.0,0.0,19.0,225.0,27.0,225.0,29.814,46.0,44.0,44.0,44.0,6.0,14.0,11.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973747,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:00:00Z,42.0,42.0,42.0,78.0,0.0,0.0,0.0,0.0,1.0,337.5,3.0,337.5,30.283,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973748,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:15:00Z,42.0,42.0,42.0,79.0,0.0,0.0,0.0,0.0,0.0,337.5,2.0,337.5,30.286,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973749,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:30:00Z,41.0,42.0,41.0,79.0,0.0,0.0,0.0,0.0,1.0,337.5,2.0,337.5,30.287,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973750,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T04:45:00Z,41.0,41.0,41.0,79.0,0.0,0.0,0.0,0.0,1.0,337.5,4.0,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0
973751,179,40.386114,-87.101296,WHIN012E-WARR002,2021-03-12T05:00:00Z,42.0,42.0,41.0,78.0,0.0,0.0,0.0,0.0,1.0,337.5,4.0,337.5,30.295,48.0,48.0,47.0,46.0,7.0,7.0,4.0,2.0

In [36]:
myDF_cleaned.isnull().sum()

station_id                     0
latitude                       0
longitude                      0
name                           0
observation_time               0
temperature                    0
temperature_high               0
temperature_low                0
humidity                       0
solar_radiation                0
solar_radiation_high           0
rain                           0
rain_inches_last_hour          0
wind_speed_mph                 0
wind_direction_degrees         0
wind_gust_speed_mph            0
wind_gust_direction_degrees    0
pressure                       0
soil_temp_1                    0
soil_temp_2                    0
soil_temp_3                    0
soil_temp_4                    0
soil_moist_1                   0
soil_moist_2                   0
soil_moist_3                   0
soil_moist_4                   0
dtype: int64

For parts a, b and c, I used all the 3 functions presented by the tip. For part b, specifically, I added another .sum() after the first .sum() function as I had to sum up all the null values in each column that I got for part a. I found this out by watching the hint video, "hints for Question 2 on TDM 10200 Project 9" linked here": https://the-examples-book.com/programming-languages/python/hints-for-TDM-10200-project-9. For the part d, to check if there were any null values remaining in myDF_cleaned, I combined the isnull() and sum() functions just like how I did with myDF when presenting the total number of null records for each column. All the 0s for part d indicate that myDF_cleaned does not have any null records present in it anymore.

## Question 3

In [3]:
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/whin/weather.csv")
pd.set_option('display.max_columns', None)
myDF.head()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
0,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.05,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0
1,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.04,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0
2,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.89,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0
3,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.88,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0
4,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.88,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0

In [68]:
myDF.dropna(subset=['temperature'])

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
0,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.050,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0
1,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.040,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0
2,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.890,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0
3,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.880,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0
4,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.880,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:30:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,2.0,90.0,4.0,NaN,30.015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999996,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:45:00Z,64.0,64.0,64.0,90.0,0.0,0.0,0.0,0.0,1.0,67.5,4.0,90.0,30.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999997,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:00:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,1.0,67.5,3.0,67.5,30.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999998,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:15:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,0.0,67.5,3.0,67.5,30.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999999,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:30:00Z,64.0,64.0,63.0,91.0,0.0,0.0,0.0,0.0,3.0,90.0,7.0,67.5,29.996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
newDF = [] 
newDF = myDF.dropna(subset=['temperature']) 
newDF

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4
0,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.050,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0
1,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.040,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0
2,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.890,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0
3,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.880,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0
4,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.880,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:30:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,2.0,90.0,4.0,NaN,30.015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999996,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T06:45:00Z,64.0,64.0,64.0,90.0,0.0,0.0,0.0,0.0,1.0,67.5,4.0,90.0,30.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999997,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:00:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,1.0,67.5,3.0,67.5,30.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999998,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:15:00Z,64.0,64.0,64.0,91.0,0.0,0.0,0.0,0.0,0.0,67.5,3.0,67.5,30.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999999,171,40.296799,-87.390285,WHIN038E-WARR004,2021-07-10T07:30:00Z,64.0,64.0,63.0,91.0,0.0,0.0,0.0,0.0,3.0,90.0,7.0,67.5,29.996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
newDF['temperature'].isnull().sum()

0

In [8]:
newDF = myDF.dropna(subset=['temperature']) 
pd.set_option('display.max_columns', None)
newDF.columns

Index(['station_id', 'latitude', 'longitude', 'name', 'observation_time',
       'temperature', 'temperature_high', 'temperature_low', 'humidity',
       'solar_radiation', 'solar_radiation_high', 'rain',
       'rain_inches_last_hour', 'wind_speed_mph', 'wind_direction_degrees',
       'wind_gust_speed_mph', 'wind_gust_direction_degrees', 'pressure',
       'soil_temp_1', 'soil_temp_2', 'soil_temp_3', 'soil_temp_4',
       'soil_moist_1', 'soil_moist_2', 'soil_moist_3', 'soil_moist_4'],
      dtype='object')

In [ ]:
newDF['location'] = newDF['latitude'].astype(str) +'_'+ newDF['longitude'].astype(str)

In [11]:
newDF.head()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4,location
0,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.05,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0,40.93894_-86.47418
1,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.04,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0,40.93894_-86.47418
2,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.89,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0,40.93894_-86.47418
3,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.88,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0,40.93894_-86.47418
4,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.88,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0,40.93894_-86.47418

In [5]:
newDF.columns

Index(['station_id', 'latitude', 'longitude', 'name', 'observation_time',
       'temperature', 'temperature_high', 'temperature_low', 'humidity',
       'solar_radiation', 'solar_radiation_high', 'rain',
       'rain_inches_last_hour', 'wind_speed_mph', 'wind_direction_degrees',
       'wind_gust_speed_mph', 'wind_gust_direction_degrees', 'pressure',
       'soil_temp_1', 'soil_temp_2', 'soil_temp_3', 'soil_temp_4',
       'soil_moist_1', 'soil_moist_2', 'soil_moist_3', 'soil_moist_4',
       'location'],
      dtype='object')

In [12]:
newDF.groupby(['location'])['temperature'].mean()

location
40.10483_-86.86619                    56.057495
40.1492432088387_-86.7371410131454    61.413324
40.16179_-87.35246                    54.052897
40.2709571472446_-87.1486035394257    49.803342
40.2967994865571_-87.3902853950858    57.855233
40.30156_-87.48248                    58.889855
40.37634_-86.59591                    54.794076
40.38116_-86.40269                    47.765668
40.3840069271445_-87.31664031744      59.552215
40.38539_-87.51034                    55.115662
40.3861140862113_-87.1012964844704    59.383360
40.42124_-86.84642                    50.742410
40.43134_-86.53464                    55.081819
40.48079_-87.20682                    51.730032
40.4869749155437_-87.4914180859923    58.971553
40.51432_-86.45856                    55.183031
40.53722_-86.95342                    55.070667
40.5485_-87.12477                     54.898998
40.58629_-87.43654                    54.676701
40.59057_-86.39155                    55.307808
40.70178_-86.70649                    55.482287
40.78049_-86.89576                    54.791890
40.84436_-86.18173                    54.942505
40.93894_-86.47418                    49.883742
40.9700622558594_-86.9013715815608    59.919768
40.97061_-86.35304                    55.292530
40.98224_-86.38542                    54.206106
41.01865_-86.7101                     53.836086
Name: temperature, dtype: float64

For part a, b and c, I read and used the information from the tip presented. For part a, I read this website: https://www.digitalocean.com/community/tutorials/pandas-dropna-drop-null-na-values-from-dataframe#dropping-rows-or-columns-if-all-the-values-are-null-with-how and got the code structure for how to drop rows with null values in 1 specific column such as 'temperature'. For part b, I read this website: https://www.statology.org/pandas-combine-two-columns/ and got the code structure for combining 2 columns in myDF and making sure that the new column, 'location' was a string. Hence, I attached the .astype(str) for both the 'latitude' and 'longitude' column based on the code structure presented. I also watched the hint video, "hints for Question 3 on TDM 10200 Project 9" linked here: https://the-examples-book.com/programming-languages/python/hints-for-TDM-10200-project-9 to check my work.

## Question 4

In [13]:
def average_temperature_by_location(data_frame): 
    myresult = newDF.groupby(['location'])['temperature'].mean() 
    return myresult

In [14]:
average_temperature_by_location(newDF)

location
40.10483_-86.86619                    56.057495
40.1492432088387_-86.7371410131454    61.413324
40.16179_-87.35246                    54.052897
40.2709571472446_-87.1486035394257    49.803342
40.2967994865571_-87.3902853950858    57.855233
40.30156_-87.48248                    58.889855
40.37634_-86.59591                    54.794076
40.38116_-86.40269                    47.765668
40.3840069271445_-87.31664031744      59.552215
40.38539_-87.51034                    55.115662
40.3861140862113_-87.1012964844704    59.383360
40.42124_-86.84642                    50.742410
40.43134_-86.53464                    55.081819
40.48079_-87.20682                    51.730032
40.4869749155437_-87.4914180859923    58.971553
40.51432_-86.45856                    55.183031
40.53722_-86.95342                    55.070667
40.5485_-87.12477                     54.898998
40.58629_-87.43654                    54.676701
40.59057_-86.39155                    55.307808
40.70178_-86.70649                    55.482287
40.78049_-86.89576                    54.791890
40.84436_-86.18173                    54.942505
40.93894_-86.47418                    49.883742
40.9700622558594_-86.9013715815608    59.919768
40.97061_-86.35304                    55.292530
40.98224_-86.38542                    54.206106
41.01865_-86.7101                     53.836086
Name: temperature, dtype: float64

In [15]:
average_temperature_by_location(myDF)

location
40.10483_-86.86619                    56.057495
40.1492432088387_-86.7371410131454    61.413324
40.16179_-87.35246                    54.052897
40.2709571472446_-87.1486035394257    49.803342
40.2967994865571_-87.3902853950858    57.855233
40.30156_-87.48248                    58.889855
40.37634_-86.59591                    54.794076
40.38116_-86.40269                    47.765668
40.3840069271445_-87.31664031744      59.552215
40.38539_-87.51034                    55.115662
40.3861140862113_-87.1012964844704    59.383360
40.42124_-86.84642                    50.742410
40.43134_-86.53464                    55.081819
40.48079_-87.20682                    51.730032
40.4869749155437_-87.4914180859923    58.971553
40.51432_-86.45856                    55.183031
40.53722_-86.95342                    55.070667
40.5485_-87.12477                     54.898998
40.58629_-87.43654                    54.676701
40.59057_-86.39155                    55.307808
40.70178_-86.70649                    55.482287
40.78049_-86.89576                    54.791890
40.84436_-86.18173                    54.942505
40.93894_-86.47418                    49.883742
40.9700622558594_-86.9013715815608    59.919768
40.97061_-86.35304                    55.292530
40.98224_-86.38542                    54.206106
41.01865_-86.7101                     53.836086
Name: temperature, dtype: float64

In [18]:
average_temperature_by_location(myDF_cleaned)

location
40.10483_-86.86619                    56.057495
40.1492432088387_-86.7371410131454    61.413324
40.16179_-87.35246                    54.052897
40.2709571472446_-87.1486035394257    49.803342
40.2967994865571_-87.3902853950858    57.855233
40.30156_-87.48248                    58.889855
40.37634_-86.59591                    54.794076
40.38116_-86.40269                    47.765668
40.3840069271445_-87.31664031744      59.552215
40.38539_-87.51034                    55.115662
40.3861140862113_-87.1012964844704    59.383360
40.42124_-86.84642                    50.742410
40.43134_-86.53464                    55.081819
40.48079_-87.20682                    51.730032
40.4869749155437_-87.4914180859923    58.971553
40.51432_-86.45856                    55.183031
40.53722_-86.95342                    55.070667
40.5485_-87.12477                     54.898998
40.58629_-87.43654                    54.676701
40.59057_-86.39155                    55.307808
40.70178_-86.70649                    55.482287
40.78049_-86.89576                    54.791890
40.84436_-86.18173                    54.942505
40.93894_-86.47418                    49.883742
40.9700622558594_-86.9013715815608    59.919768
40.97061_-86.35304                    55.292530
40.98224_-86.38542                    54.206106
41.01865_-86.7101                     53.836086
Name: temperature, dtype: float64

For question 4, I just brought all my work from question 3 and created the function. I used the newDF data frame because to create this data frame, I had dropped the rows that had null values for the temperature column. Hence, I used the newDF data frame to calculate the average temperature by sorting the values in terms of the new column ('location') created. I also tested my function with newDF, myDF and myDF_cleaned to check if all 3 data frames gave the same output as intended before I created the function. The very fact that myDF (not modified for null temperature values) also shows the same output as newDF means that in this function, myDF first has to drop all null rows with null temperature values which is stored in as the newDF. Using the newDF, where all rows with null temperature values have been dropped, the average temperature is calculated by grouping the data in terms of the new column ('location') created.

## Question 5

In [6]:
newDF = myDF.dropna(subset=['wind_gust_speed_mph']) 
pd.set_option('display.max_columns', None)
newDF.columns

Index(['station_id', 'latitude', 'longitude', 'name', 'observation_time',
       'temperature', 'temperature_high', 'temperature_low', 'humidity',
       'solar_radiation', 'solar_radiation_high', 'rain',
       'rain_inches_last_hour', 'wind_speed_mph', 'wind_direction_degrees',
       'wind_gust_speed_mph', 'wind_gust_direction_degrees', 'pressure',
       'soil_temp_1', 'soil_temp_2', 'soil_temp_3', 'soil_temp_4',
       'soil_moist_1', 'soil_moist_2', 'soil_moist_3', 'soil_moist_4'],
      dtype='object')

In [ ]:
newDF['location'] = newDF['latitude'].astype(str) + '_' + newDF['longitude'].astype(str)

In [26]:
newDF.head()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4,location
0,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.05,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0,40.93894_-86.47418
1,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.04,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0,40.93894_-86.47418
2,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.89,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0,40.93894_-86.47418
3,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.88,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0,40.93894_-86.47418
4,1,40.93894,-86.47418,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.88,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0,40.93894_-86.47418

In [27]:
newDF.columns

Index(['station_id', 'latitude', 'longitude', 'name', 'observation_time',
       'temperature', 'temperature_high', 'temperature_low', 'humidity',
       'solar_radiation', 'solar_radiation_high', 'rain',
       'rain_inches_last_hour', 'wind_speed_mph', 'wind_direction_degrees',
       'wind_gust_speed_mph', 'wind_gust_direction_degrees', 'pressure',
       'soil_temp_1', 'soil_temp_2', 'soil_temp_3', 'soil_temp_4',
       'soil_moist_1', 'soil_moist_2', 'soil_moist_3', 'soil_moist_4',
       'location'],
      dtype='object')

In [20]:
newDF.groupby(['location'])['wind_gust_speed_mph'].mean()

location
40.10483_-86.86619                    10.563551
40.1492432088387_-86.7371410131454    10.136323
40.16179_-87.35246                     9.032308
40.2709571472446_-87.1486035394257     9.994114
40.2967994865571_-87.3902853950858    11.560288
40.30156_-87.48248                    10.205555
40.37634_-86.59591                    10.174628
40.38116_-86.40269                    12.851717
40.3840069271445_-87.31664031744       6.184488
40.38539_-87.51034                    11.075945
40.3861140862113_-87.1012964844704     7.812415
40.42124_-86.84642                     5.974205
40.43134_-86.53464                    11.226786
40.48079_-87.20682                     6.290474
40.4869749155437_-87.4914180859923    11.720362
40.51432_-86.45856                    10.181839
40.53722_-86.95342                    11.794791
40.5485_-87.12477                     10.516033
40.58629_-87.43654                    11.681777
40.59057_-86.39155                    10.055651
40.70178_-86.70649                    10.139477
40.78049_-86.89576                    10.855496
40.84436_-86.18173                    10.285534
40.93894_-86.47418                     9.945019
40.9700622558594_-86.9013715815608    11.544695
40.97061_-86.35304                    10.843384
40.98224_-86.38542                    10.964359
41.01865_-86.7101                      8.976051
Name: wind_gust_speed_mph, dtype: float64

In [21]:
def average_wind_gust_speed_mph_by_location(data_frame): 
    myresult = newDF.groupby(['location'])['wind_gust_speed_mph'].mean() 
    return myresult

In [22]:
average_wind_gust_speed_mph_by_location(myDF)

location
40.10483_-86.86619                    10.563551
40.1492432088387_-86.7371410131454    10.136323
40.16179_-87.35246                     9.032308
40.2709571472446_-87.1486035394257     9.994114
40.2967994865571_-87.3902853950858    11.560288
40.30156_-87.48248                    10.205555
40.37634_-86.59591                    10.174628
40.38116_-86.40269                    12.851717
40.3840069271445_-87.31664031744       6.184488
40.38539_-87.51034                    11.075945
40.3861140862113_-87.1012964844704     7.812415
40.42124_-86.84642                     5.974205
40.43134_-86.53464                    11.226786
40.48079_-87.20682                     6.290474
40.4869749155437_-87.4914180859923    11.720362
40.51432_-86.45856                    10.181839
40.53722_-86.95342                    11.794791
40.5485_-87.12477                     10.516033
40.58629_-87.43654                    11.681777
40.59057_-86.39155                    10.055651
40.70178_-86.70649                    10.139477
40.78049_-86.89576                    10.855496
40.84436_-86.18173                    10.285534
40.93894_-86.47418                     9.945019
40.9700622558594_-86.9013715815608    11.544695
40.97061_-86.35304                    10.843384
40.98224_-86.38542                    10.964359
41.01865_-86.7101                      8.976051
Name: wind_gust_speed_mph, dtype: float64

In [23]:
average_wind_gust_speed_mph_by_location(newDF)

location
40.10483_-86.86619                    10.563551
40.1492432088387_-86.7371410131454    10.136323
40.16179_-87.35246                     9.032308
40.2709571472446_-87.1486035394257     9.994114
40.2967994865571_-87.3902853950858    11.560288
40.30156_-87.48248                    10.205555
40.37634_-86.59591                    10.174628
40.38116_-86.40269                    12.851717
40.3840069271445_-87.31664031744       6.184488
40.38539_-87.51034                    11.075945
40.3861140862113_-87.1012964844704     7.812415
40.42124_-86.84642                     5.974205
40.43134_-86.53464                    11.226786
40.48079_-87.20682                     6.290474
40.4869749155437_-87.4914180859923    11.720362
40.51432_-86.45856                    10.181839
40.53722_-86.95342                    11.794791
40.5485_-87.12477                     10.516033
40.58629_-87.43654                    11.681777
40.59057_-86.39155                    10.055651
40.70178_-86.70649                    10.139477
40.78049_-86.89576                    10.855496
40.84436_-86.18173                    10.285534
40.93894_-86.47418                     9.945019
40.9700622558594_-86.9013715815608    11.544695
40.97061_-86.35304                    10.843384
40.98224_-86.38542                    10.964359
41.01865_-86.7101                      8.976051
Name: wind_gust_speed_mph, dtype: float64

In [28]:
average_wind_gust_speed_mph_by_location(myDF_cleaned)

location
40.10483_-86.86619                    10.563551
40.1492432088387_-86.7371410131454    10.136323
40.16179_-87.35246                     9.032308
40.2709571472446_-87.1486035394257     9.994114
40.2967994865571_-87.3902853950858    11.560288
40.30156_-87.48248                    10.205555
40.37634_-86.59591                    10.174628
40.38116_-86.40269                    12.851717
40.3840069271445_-87.31664031744       6.184488
40.38539_-87.51034                    11.075945
40.3861140862113_-87.1012964844704     7.812415
40.42124_-86.84642                     5.974205
40.43134_-86.53464                    11.226786
40.48079_-87.20682                     6.290474
40.4869749155437_-87.4914180859923    11.720362
40.51432_-86.45856                    10.181839
40.53722_-86.95342                    11.794791
40.5485_-87.12477                     10.516033
40.58629_-87.43654                    11.681777
40.59057_-86.39155                    10.055651
40.70178_-86.70649                    10.139477
40.78049_-86.89576                    10.855496
40.84436_-86.18173                    10.285534
40.93894_-86.47418                     9.945019
40.9700622558594_-86.9013715815608    11.544695
40.97061_-86.35304                    10.843384
40.98224_-86.38542                    10.964359
41.01865_-86.7101                      8.976051
Name: wind_gust_speed_mph, dtype: float64

In [25]:
newDF.groupby('location')['wind_gust_speed_mph'].mean().idxmax()

'40.38116_-86.40269'

For part a, I used the same code structure as I did for question 3 and 4. However, I replaced 'temperature' with 'wind_gust_speed_mph' to meet this question's requirements. After doing this, I created my function and labelled it as 'average_wind_gust_speed_mph_by_location' because this function is now supposed to calculate the average wind gust speed mph values instead of the average temperatures. I also tested the function for myDF, newDF and myDF_cleaned to check my output and I found that it remained the same. For part b, I got the code structure from the work I had done in project 7, question 5 to find the location with the largest average wind_gust_speed_mph value. To find this location, I used the idxmax() function and got the desired output.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.