# Project 6 -- [Niharika] [Rai]

**TA Help:** N/A
    
**Collaboration:** N/A

## Question 1

In [12]:
myyear = 1980 
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt'
myfilepath

'/anvil/projects/tdm/data/election/itcont1980.txt'

In [13]:
myyear = 1984 
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt'
myfilepath

'/anvil/projects/tdm/data/election/itcont1984.txt'

In [14]:
myyear = 1988 
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt'
myfilepath

'/anvil/projects/tdm/data/election/itcont1988.txt'

In [18]:
myyear = 1980
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt' 
mycolumnnames=["CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP","NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT","OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"]
mydictionarytypes = dtype_dict = {"CMTE_ID": str, "AMNDT_IND": str, "RPT_TP": str, "TRANSACTION_PGI": str, "IMAGE_NUM": str, "TRANSACTION_TP": str, "ENTITY_TP": str, "NAME": str, "CITY": str, "STATE": str, "ZIP_CODE": str, "EMPLOYER": str, "OCCUPATION": str, "TRANSACTION_DT": str, "TRANSACTION_AMT": float, "OTHER_ID": str, "TRAN_ID": str, "FILE_NUM": str, "MEMO_CD": str, "MEMO_TEXT": str, "SUB_ID": int}
myDF = pd.read_csv(myfilepath, delimiter='|', names=mycolumnnames, dtype=mydictionarytypes)
myDF['TRANSACTION_DT'] = pd.to_datetime(myDF['TRANSACTION_DT'], format="%m%d%Y") 
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,1979-10-03,400.0,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,1500.0,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,300.0,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,1979-03-20,200.0,NaN,NaN,NaN,NaN,NaN,3061920110000383914

In [19]:
myyear = 1984
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt' 
mycolumnnames=["CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP","NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT","OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"]
mydictionarytypes = dtype_dict = {"CMTE_ID": str, "AMNDT_IND": str, "RPT_TP": str, "TRANSACTION_PGI": str, "IMAGE_NUM": str, "TRANSACTION_TP": str, "ENTITY_TP": str, "NAME": str, "CITY": str, "STATE": str, "ZIP_CODE": str, "EMPLOYER": str, "OCCUPATION": str, "TRANSACTION_DT": str, "TRANSACTION_AMT": float, "OTHER_ID": str, "TRAN_ID": str, "FILE_NUM": str, "MEMO_CD": str, "MEMO_TEXT": str, "SUB_ID": int}
myDF = pd.read_csv(myfilepath, delimiter='|', names=mycolumnnames, dtype=mydictionarytypes)
myDF['TRANSACTION_DT'] = pd.to_datetime(myDF['TRANSACTION_DT'], format="%m%d%Y") 
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00146845,N,MY,NaN,83012471866,15,NaN,"ANDREWS, STEPHEN K",INDPLS,IN,...,ATTORNEY,NaN,1983-02-28,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001124709
1,C00167973,A,MY,NaN,83012481756,15,NaN,"ZARO, CHRISTOPHER",WAYNE,PA,...,REAL ESTATE DEVELOPER,NaN,1983-01-28,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001112098
2,C00167973,A,MY,NaN,83012481756,15,NaN,"KOPROWSKI, CHRISTOPHER D MD",HAVERTOWN,PA,...,SELF-EMPLOYED,NaN,1983-06-29,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001112099
3,C00167973,A,MY,NaN,83012481756,15,NaN,"KOPROWSKI, MARY MCLAUGHLIN MD",HAVERTOWN,PA,...,PHYSICIAN,NaN,1983-06-29,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001112100
4,C00167973,A,MY,NaN,83012481757,15C,NaN,"PETERS, FREDERICK C II",NaN,NaN,...,NaN,NaN,1983-01-03,500.0,H4PA07019,NaN,NaN,NaN,NaN,3061920110001112101

In [20]:
myyear = 1988
myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt' 
mycolumnnames=["CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP","NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT","OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"]
mydictionarytypes = dtype_dict = {"CMTE_ID": str, "AMNDT_IND": str, "RPT_TP": str, "TRANSACTION_PGI": str, "IMAGE_NUM": str, "TRANSACTION_TP": str, "ENTITY_TP": str, "NAME": str, "CITY": str, "STATE": str, "ZIP_CODE": str, "EMPLOYER": str, "OCCUPATION": str, "TRANSACTION_DT": str, "TRANSACTION_AMT": float, "OTHER_ID": str, "TRAN_ID": str, "FILE_NUM": str, "MEMO_CD": str, "MEMO_TEXT": str, "SUB_ID": int}
myDF = pd.read_csv(myfilepath, delimiter='|', names=mycolumnnames, dtype=mydictionarytypes)
myDF['TRANSACTION_DT'] = pd.to_datetime(myDF['TRANSACTION_DT'], format="%m%d%Y") 
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00015263,N,MY,NaN,87013363162,15,NaN,"ARNOLD, CARL",MCLEAN,VA,...,NaN,NaN,1987-06-13,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001680883
1,C00015263,N,MY,NaN,87013363162,15,NaN,"HUSTON, CHARLES L III",CHESTER SPRINGS,PA,...,NaN,NaN,1987-06-13,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001680884
2,C00015263,N,MY,NaN,87013363162,15,NaN,"WALL, R DUFFY",HURLOCK,MD,...,NaN,NaN,1987-06-30,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001680885
3,C00170506,N,MY,NaN,87013363893,15C,NaN,NaN,NaN,NaN,...,NaN,NaN,1987-01-31,2378.0,H4MO09012,NaN,NaN,NaN,NaN,3061920110001714528
4,C00170506,N,MY,NaN,87013363893,15C,NaN,NaN,NaN,NaN,...,NaN,NaN,1987-04-04,3044.0,H4MO09012,NaN,NaN,NaN,NaN,3061920110001714529

In [2]:
import pandas as pd 
def read_election_year(myyear: int) -> pd.DataFrame: 
    """
    
    read_election_year is a fuction that takes the year an input and outputs the resulting data frame for that year. The data frame contains real-life information about the donations made by people for the federal election campaigns during the year entered as the input. 
    
    Args: 
    
    myyear(int): This is the parameter where the year will be fed in which will in turn return the data frame associated with this year. 
    
    Returns: 
    
    myDF(pd.DataFrame): This will give the output which will be the data frame for the year entered as the input. When the data frame is read, it will show you the information about the donations made for the federal election campaigns. 
    
    """
    myfilepath = f'/anvil/projects/tdm/data/election/itcont{myyear}.txt' 
    mycolumnnames=["CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","ENTITY_TP","NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT","OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"]
    mydictionarytypes = dtype_dict = {"CMTE_ID": str, "AMNDT_IND": str, "RPT_TP": str, "TRANSACTION_PGI": str, "IMAGE_NUM": str, "TRANSACTION_TP": str, "ENTITY_TP": str, "NAME": str, "CITY": str, "STATE": str, "ZIP_CODE": str, "EMPLOYER": str, "OCCUPATION": str, "TRANSACTION_DT": str, "TRANSACTION_AMT": float, "OTHER_ID": str, "TRAN_ID": str, "FILE_NUM": str, "MEMO_CD": str, "MEMO_TEXT": str, "SUB_ID": int}
    myDF = pd.read_csv(myfilepath, delimiter='|', names=mycolumnnames, dtype=mydictionarytypes)
    myDF['TRANSACTION_DT'] = pd.to_datetime(myDF['TRANSACTION_DT'], format="%m%d%Y")
    return myDF

In [3]:
myDF = read_election_year(1980)
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,1979-10-03,400.0,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,1500.0,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,300.0,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,1979-10-26,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,1979-03-20,200.0,NaN,NaN,NaN,NaN,NaN,3061920110000383914

In [29]:
myDF = read_election_year(1984)
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00146845,N,MY,NaN,83012471866,15,NaN,"ANDREWS, STEPHEN K",INDPLS,IN,...,ATTORNEY,NaN,1983-02-28,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001124709
1,C00167973,A,MY,NaN,83012481756,15,NaN,"ZARO, CHRISTOPHER",WAYNE,PA,...,REAL ESTATE DEVELOPER,NaN,1983-01-28,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001112098
2,C00167973,A,MY,NaN,83012481756,15,NaN,"KOPROWSKI, CHRISTOPHER D MD",HAVERTOWN,PA,...,SELF-EMPLOYED,NaN,1983-06-29,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001112099
3,C00167973,A,MY,NaN,83012481756,15,NaN,"KOPROWSKI, MARY MCLAUGHLIN MD",HAVERTOWN,PA,...,PHYSICIAN,NaN,1983-06-29,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001112100
4,C00167973,A,MY,NaN,83012481757,15C,NaN,"PETERS, FREDERICK C II",NaN,NaN,...,NaN,NaN,1983-01-03,500.0,H4PA07019,NaN,NaN,NaN,NaN,3061920110001112101

In [30]:
myDF = read_election_year(1988)
myDF.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00015263,N,MY,NaN,87013363162,15,NaN,"ARNOLD, CARL",MCLEAN,VA,...,NaN,NaN,1987-06-13,500.0,NaN,NaN,NaN,NaN,NaN,3061920110001680883
1,C00015263,N,MY,NaN,87013363162,15,NaN,"HUSTON, CHARLES L III",CHESTER SPRINGS,PA,...,NaN,NaN,1987-06-13,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001680884
2,C00015263,N,MY,NaN,87013363162,15,NaN,"WALL, R DUFFY",HURLOCK,MD,...,NaN,NaN,1987-06-30,1000.0,NaN,NaN,NaN,NaN,NaN,3061920110001680885
3,C00170506,N,MY,NaN,87013363893,15C,NaN,NaN,NaN,NaN,...,NaN,NaN,1987-01-31,2378.0,H4MO09012,NaN,NaN,NaN,NaN,3061920110001714528
4,C00170506,N,MY,NaN,87013363893,15C,NaN,NaN,NaN,NaN,...,NaN,NaN,1987-04-04,3044.0,H4MO09012,NaN,NaN,NaN,NaN,3061920110001714529

For this question, I watched the second, third and the fourth videos uploaded by Dr. Ward in the examples textbook: https://the-examples-book.com/programming-languages/python/some-examples-for-TDM-10200-project-6. From these videos, I got the basic code structure to solve each of the parts and also understood the concept of a docstring better. Hence, I first tested out the values to find out what the final output of my function should be. Later, I built the function and tested that function to see if I got the desired output or not.

## Question 2

In [5]:
myyear = 1980 
myDF = read_election_year(myyear)
len(myDF['CMTE_ID'].unique())

3856

In [6]:
myyear = 1984
myDF = read_election_year(myyear)
len(myDF['CMTE_ID'].unique())

3733

In [7]:
myyear = 1988 
myDF = read_election_year(myyear)
len(myDF['CMTE_ID'].unique())

3995

In [20]:
def committees_function(myyear: int) -> int: 
    myDF = read_election_year(myyear) 
    myresult = len(myDF['CMTE_ID'].unique())
    return myresult

In [21]:
committees_function(1980)

3856

In [22]:
committees_function(1984)

3733

In [23]:
committees_function(1988)

3995

For part a, I used the len and unique function to get to my output. This output is what I also wanted my function to return. Hence, I watch the fifth video here: https://the-examples-book.com/programming-languages/python/some-examples-for-TDM-10200-project-6. This gave the code structure of: 

myDF = read_election_year(myyear) 
myresult = len(myDF['CMTE_ID'].unique())

Hence, I used these codes to form the output and create the function for part b. After watchihg this video, I also learned how to used the python function from the previous question to solve this question.

## Question 3

In [13]:
myDF = read_election_year(1980)
myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values()

STATE
TU         250.0
BE         750.0
CZ         950.0
EL        1000.0
AS        1500.0
         ...
IL     9105545.0
FL    10514203.0
NY    18673301.0
CA    24085171.0
TX    24472610.0
Name: TRANSACTION_AMT, Length: 61, dtype: float64

In [28]:
myDF = read_election_year(1980)
myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values().tail()

STATE
IL     9105545.0
FL    10514203.0
NY    18673301.0
CA    24085171.0
TX    24472610.0
Name: TRANSACTION_AMT, dtype: float64

In [29]:
myDF = read_election_year(1984)
myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values().tail()

STATE
IL    10034785.0
FL    10985587.0
NY    25947339.0
CA    29265671.0
TX    36044231.0
Name: TRANSACTION_AMT, dtype: float64

In [32]:
myDF = read_election_year(1988) 
myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values().tail()

STATE
NJ    18934575.0
FL    25373272.0
TX    29076324.0
NY    49898456.0
CA    60239357.0
Name: TRANSACTION_AMT, dtype: float64

In [33]:
import pandas as pd 
def top_five_states(myyear = int) -> pd.DataFrame: 
    myDF = read_election_year(myyear)
    myresult = myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values().tail() 
    return myresult

In [34]:
top_five_states(1980)

STATE
IL     9105545.0
FL    10514203.0
NY    18673301.0
CA    24085171.0
TX    24472610.0
Name: TRANSACTION_AMT, dtype: float64

In [35]:
top_five_states(1984)

STATE
IL    10034785.0
FL    10985587.0
NY    25947339.0
CA    29265671.0
TX    36044231.0
Name: TRANSACTION_AMT, dtype: float64

In [36]:
top_five_states(1988)

STATE
NJ    18934575.0
FL    25373272.0
TX    29076324.0
NY    49898456.0
CA    60239357.0
Name: TRANSACTION_AMT, dtype: float64

I got the below 2 code structures by watching the 6th video here: https://the-examples-book.com/programming-languages/python/some-examples-for-TDM-10200-project-6. 

myDF = read_election_year(1980)
myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values()

However, the question asked to print the ouput for only the top 5 states. Since the second line of the code above, sorted the states and their transaction amounts in ascending order, I used the tail function to print out the bottom 5 values because I knew that they were the highest. I then used all of these code lines and built the function as required by the question. But, one thing extra I did was to assign the final calculation of sorting the transaction amounts and printing the top 5 states to another new variable called myresult. This made it easier to get the output as I just had to type: return myresult to finalize the function.

## Question 4

In [20]:
myDF = read_election_year(1980)
myDF.groupby('EMPLOYER')['TRANSACTION_AMT'].sum().sort_values()

EMPLOYER
N AMERICAN SYSTEMS            -2000.0
HOLIDAY INN-DISNEY EAST       -2000.0
LEASE/SALES EQMT              -1000.0
MIDWEST FABRICATION CO        -1000.0
FIRST NAT BANK OF DALTON       -500.0
                              ...
HOUSE WIFE                  4549216.0
HOMEMAKER                   4649872.0
HOUSEWIFE                   5457943.0
ATTORNEY                    5689870.0
RETIRED                     8565354.0
Name: TRANSACTION_AMT, Length: 87347, dtype: float64

In [21]:
myDF = read_election_year(1980)
myDF.groupby('EMPLOYER')['TRANSACTION_AMT'].sum().sort_values().tail()

EMPLOYER
HOUSE WIFE    4549216.0
HOMEMAKER     4649872.0
HOUSEWIFE     5457943.0
ATTORNEY      5689870.0
RETIRED       8565354.0
Name: TRANSACTION_AMT, dtype: float64

In [22]:
myDF = read_election_year(1984)
myDF.groupby('EMPLOYER')['TRANSACTION_AMT'].sum().sort_values().tail()

EMPLOYER
HOMEMAKER         3372784.0
SELF EMPLOYED     3869043.0
HOUSEWIFE         6313918.0
RETIRED           9257779.0
SELF-EMPLOYED    19761941.0
Name: TRANSACTION_AMT, dtype: float64

In [23]:
myDF = read_election_year(1988)
myDF.groupby('EMPLOYER')['TRANSACTION_AMT'].sum().sort_values().tail()

EMPLOYER
PHYSICIAN     3104940.0
RETIRED       5865073.0
ATTORNEY      9488872.0
HOMEMAKER     9834325.0
HOUSEWIFE    14626839.0
Name: TRANSACTION_AMT, dtype: float64

In [24]:
def top_employers(myyear = int): 
    myDF = read_election_year(myyear)
    myresult = myDF.groupby('EMPLOYER')['TRANSACTION_AMT'].sum().sort_values().tail() 
    return myresult

In [25]:
top_employers(1980)

EMPLOYER
HOUSE WIFE    4549216.0
HOMEMAKER     4649872.0
HOUSEWIFE     5457943.0
ATTORNEY      5689870.0
RETIRED       8565354.0
Name: TRANSACTION_AMT, dtype: float64

In [26]:
top_employers(1984)

EMPLOYER
HOMEMAKER         3372784.0
SELF EMPLOYED     3869043.0
HOUSEWIFE         6313918.0
RETIRED           9257779.0
SELF-EMPLOYED    19761941.0
Name: TRANSACTION_AMT, dtype: float64

In [27]:
top_employers(1988)

EMPLOYER
PHYSICIAN     3104940.0
RETIRED       5865073.0
ATTORNEY      9488872.0
HOMEMAKER     9834325.0
HOUSEWIFE    14626839.0
Name: TRANSACTION_AMT, dtype: float64

Question 4 had the same concept as question 3. So, I used the general code structure from question 3: myDF.groupby('STATE')['TRANSACTION_AMT'].sum().sort_values().tail() 
However, I replaced 'STATE' with 'EMPLOYER' to sort out the transactions based on the employers. I then used the tail function to print out the employers with the top 5 highest transaction amounts. Once, I tested my output for the different years, I then built my function. Also, one thing extra I did was to assign the final calculation of sorting the transaction amounts and printing the top 5 employers to another new variable called myresult. This made it easier to get the output as I just had to type: return myresult to finalize the function.

## Question 5

In [6]:
myDF = read_election_year(1980)
myDF.groupby('NAME')['TRANSACTION_AMT'].sum().sort_values()

NAME
MITCHELL, LOUIS S                                -4567.0
RITTER, LOUIS                                    -3000.0
WILLIAMS, JACK T 2ND                             -2000.0
NEWMAN, PHIL                                     -2000.0
NEWMAN, RUTHIS                                   -2000.0
                                                 ...
MACKAY, KENNETH H JR                            527329.0
STONER, TOM                                     901381.0
AMERICAN MEDICAL POLITICAL ACTION COMMITTEE    1300341.0
KOCH, DAVID HAMILTON                           1675300.0
STEVENS, EARL VERN BLACKJACK                   6500000.0
Name: TRANSACTION_AMT, Length: 217645, dtype: float64

In [38]:
myDF = read_election_year(1980)
myDF.groupby('NAME')['TRANSACTION_AMT'].sum().sort_values().tail()

NAME
MACKAY, KENNETH H JR                            527329.0
STONER, TOM                                     901381.0
AMERICAN MEDICAL POLITICAL ACTION COMMITTEE    1300341.0
KOCH, DAVID HAMILTON                           1675300.0
STEVENS, EARL VERN BLACKJACK                   6500000.0
Name: TRANSACTION_AMT, dtype: float64

In [39]:
myDF = read_election_year(1984)
myDF.groupby('NAME')['TRANSACTION_AMT'].sum().sort_values().tail()

NAME
LEVIN, ADAM K                                               864741.0
DAYTON, MARK B                                             1309474.0
MOSBACHER, ROB                                             1447800.0
SHAMIE, RAYMOND                                            1570241.0
AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION COMMITTEE    2171333.0
Name: TRANSACTION_AMT, dtype: float64

In [46]:
myDF = read_election_year(1988)
myDF.groupby('NAME')['TRANSACTION_AMT'].sum().sort_values().tail()

NAME
TEXAS MEDICAL ASSOCIATION POLITICAL ACTION COMMITTEE-TEXPAC     486555.0
FRIENDS OF PAUL TRIBLE                                          627008.0
NATIONAL REPUBLICAN CONGRESSIONAL COMMITTEE CONTRIBUTIONS       652346.0
CALIFORNIA MEDICAL POLITICAL ACTION COMMITTEE                   705110.0
NATIONAL REPUBLICAN SENATORIAL COMMITTEE - CONTRIBUTIONS *     1602947.0
Name: TRANSACTION_AMT, dtype: float64

In [47]:
def top_5_people_who_contributed_the_most(myyear = int):
    myDF = read_election_year(myyear)
    myresult = myDF.groupby('NAME')['TRANSACTION_AMT'].sum().sort_values().tail()
    return myresult

In [48]:
top_5_people_who_contributed_the_most(1980)

NAME
MACKAY, KENNETH H JR                            527329.0
STONER, TOM                                     901381.0
AMERICAN MEDICAL POLITICAL ACTION COMMITTEE    1300341.0
KOCH, DAVID HAMILTON                           1675300.0
STEVENS, EARL VERN BLACKJACK                   6500000.0
Name: TRANSACTION_AMT, dtype: float64

In [49]:
top_5_people_who_contributed_the_most(1984)

NAME
LEVIN, ADAM K                                               864741.0
DAYTON, MARK B                                             1309474.0
MOSBACHER, ROB                                             1447800.0
SHAMIE, RAYMOND                                            1570241.0
AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION COMMITTEE    2171333.0
Name: TRANSACTION_AMT, dtype: float64

In [50]:
top_5_people_who_contributed_the_most(1988)

NAME
TEXAS MEDICAL ASSOCIATION POLITICAL ACTION COMMITTEE-TEXPAC     486555.0
FRIENDS OF PAUL TRIBLE                                          627008.0
NATIONAL REPUBLICAN CONGRESSIONAL COMMITTEE CONTRIBUTIONS       652346.0
CALIFORNIA MEDICAL POLITICAL ACTION COMMITTEE                   705110.0
NATIONAL REPUBLICAN SENATORIAL COMMITTEE - CONTRIBUTIONS *     1602947.0
Name: TRANSACTION_AMT, dtype: float64

For question 5, part a, I first looked the elections data that I read in question 1 to find out what another unique column I could pick out. So, I decided that the names column was one interesting thing, given that these names were real people, who made their contributions for the federal elections campaign, back in the 1980s. So, I followed the same pattern as question 3 and 4. However, instead of 'STATE' or 'EMPLOYER', I used 'NAME' to find out the individuals who contributed the most to the federal election campaigns in 1980, 1984, and 1988. I then used the tail function to find the top 5 people who made the most donations. This helped me to create the function that took in the year as the input and returned the names of the individuals along with the sum of their transaction amounts. I thought that by doing this, I could find a common individual who is known for contributing the most in donations every year. But by looking at all my 3 outputs, I didn't find any common name. One thing I did notice was that for years 1980 and 1984, "AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION COMMITTEE" was one common name that made the top 5 contributions for the federal election campaigns.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.